server:
  port: 9095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FLIGHT-BOOKING
  data:
    mongodb:
      url: mongodb://localhost:27017/flightbookingdb
      host: localhost
      port: 27017
      database: flightbookingdb
      repositories:
        enabled: true
